### ISSUE TITLE
Broken encoding for cyrillic rows

### ISSUE THREAD

**Issue by RyabykinIlya** [stuartemiddleton/geoparsepy#10]
You write: "_Download pre-processed **UTF-8** encoded SQL table dumps from OSM image dated dec 2019_"
But database which generated dumps was English_United States.1252 encoding
Because of that we have invalid data in sql files :(
<img width="1672" alt="Screen Shot 2023-12-30 at 1 25 51 PM" src="https://github.com/stuartemiddleton/geoparsepy/assets/28308859/be6ec671-f8df-4d8d-9bc5-e69fc1ce3b4c">

There are some rows without localization:
<img width="1672" alt="Screen Shot 2023-12-30 at 1 45 32 PM" src="https://github.com/stuartemiddleton/geoparsepy/assets/28308859/434b0f42-2e3e-4d1a-9847-46b2300066c4">

Do I need to Osm2pgsql? Or there is some other solution?

**Comment by stuartemiddleton** [comment]
lib expects database to be UTF-8 encoded SQL
yes, osm2pgsql is needed to create your own SQL dumps. see readme section: Databases needed for preprocessing focus areas (optional)
