### ISSUE TITLE
Database setup fails

### ISSUE THREAD

**Issue by daveekr** [stuartemiddleton/geoparsepy#3]
Hi,

I started several attempts to setup the database required for geoparsepy. However I failed to do so on several devices and environments. I tried it on macOS locally and with Docker, same on Windows. I am not 100 % certain but I think the encoding of the sql Files is somehow messed up. Also I am struggling to setup the collation from the sql-Files.

Can anyone confirm that the dumps actually work and maybe give some advice?

Thanks in advance.

**Comment by stuartemiddleton** [comment]
the encoding of the SQL files on google drive link is UTF-8 and it should have size 1.2Gbytes (zipped and tar). I suggest you have downloaded the files OK, that they unzip and untar OK. Postgres should expect UTF-8 unless you have configured it differently.

others have got it working OK (look at the closed geoparsepy issues), so the SQL files themselves should be fine.

you have not reported the errors you get. the commands for installing the database are in the readme. if you are using Win10 then this link has some help setting up the client encoding correctly [stackoverflow](https://stackoverflow.com/questions/20952893/postgresql-encoding-problems-on-windows-when-using-psql-command-line-utility)
