### ISSUE TITLE
Missing data for columan "tags"

### ISSUE THREAD

**Issue by chouisgiser** [stuartemiddleton/geoparsepy#8]
Dear Stuart,

When I restore the table of uk_places using your provided "uk_places.sql" file, I encountered the error "missing data for column "tags" CONTEXT:  COPY uk_places_point, line 1: "1	Aaron's Hill	{718482994}	{-151304,-62149,-58447,-57582}	0101000020E6100000C737CAB0402AE4BFC8A9E7EE..."". I checked the content of sql file and suspected that there are some empty values for the column tags, e.g., the first row, Aaron's Hill. 

I am wondering if there is a solution to resolve it? E.g., using '' to fill the empty values? 

Thanks in avance.

**Comment by stuartemiddleton** [comment]
Others have used the SQL file with no problems (including myself). Maybe its a local postgres config issue you have not allowing empty values? The instructions have exactly the commands I used successfully myself.

**Comment by chouisgiser** [comment]
> 

Thanks a lot for your confirmation, Dr. Middleton, then I will have a more careful check and setting.
